CDR GENERATION:
  DATA DENSITY: 10                              # Average number of CDR per day per user
  TIME PERIOD: ['2021-01-01', '2021-01-07']     # Date period for which to calculate synthetic CDR, both sides inclusive


REFERENCE:
  CELLS: 'ref_data/ee_cells.csv'                # Input data in the form of cells, usually from OpenCellID. Uses the columns 'cell', 'lat' and 'lon'
  # TODO: Make custom column formats somehow acceptable

OUTPUT:
  CDR: 'output_files/cdr_files'                 # Output folder for synthetic CDR data
  CELLS: 'output_files/cell_location_files'     # Output folder for cell location files
  METADATA: 'output_files/metadata_files'       # Output folder for synthetic CDR metadata (users, profiles and meaningful locations)