CDR GENERATION:
  DATA DENSITY: 10
  TIME PERIOD: ['2021-01-01', '2021-01-07']


REFERENCE:
  CELLS: 'ref_data/ee_cells.csv'

OUTPUT:
  CDR: 'output_files/cdr_files'
  CELLS: 'output_files/cell_location_files'
  METADATA: 'output_files/metadata_files'